# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

forward_interface <- function(log_emission_mat, initial_prob_vec, transition_mat) {
    .Call(`_plotHMM_forward_interface`, log_emission_mat, initial_prob_vec, transition_mat)
}

