# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

forward_interface <- function(log_emission_mat, transition_mat, initial_prob_vec) {
    .Call(`_plotHMM_forward_interface`, log_emission_mat, transition_mat, initial_prob_vec)
}

backward_interface <- function(log_emission_mat, transition_mat) {
    .Call(`_plotHMM_backward_interface`, log_emission_mat, transition_mat)
}

multiply_interface <- function(log_alpha_mat, log_beta_mat) {
    .Call(`_plotHMM_multiply_interface`, log_alpha_mat, log_beta_mat)
}

pairwise_interface <- function(log_emission_mat, transition_mat, log_alpha_mat, log_beta_mat) {
    .Call(`_plotHMM_pairwise_interface`, log_emission_mat, transition_mat, log_alpha_mat, log_beta_mat)
}

transition_interface <- function(log_gamma_mat, log_xi_array) {
    .Call(`_plotHMM_transition_interface`, log_gamma_mat, log_xi_array)
}

